language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
os:
  - linux
  - osx
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  export CXX="g++-4.8" CC="gcc-4.8"
matrix:
  fast_finish: true
