language: node_js
node_js:
  - "8"
  - "6"
  - "4"
  - "0.12"
  - "0.10"
os:
  - linux
  - osx
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
before_install:
  if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
matrix:
  fast_finish: true
