# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "6"

platform:
  - x86
  - x64

install:
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Install-Product node $env:nodejs_version
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform
  - node -p process.arch
  - node -p process.version
  # Temporary workaround for https://github.com/nodejs/node-gyp/pull/952
  - npm install -g npm
  - IF %nodejs_version% LSS 1 set PATH=%APPDATA%\npm;%PATH%
  # Typical npm stuff.
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"

matrix:
  fast_finish: true
